### ISSUE TITLE
Execution aborted when running: kstool x64 "vaddpd zmm1, zmm1, zmm1:["

### ISSUE THREAD

**Issue by practicalswift** [keystone-engine/keystone#180]
```
$ kstool x64 "vaddpd zmm1, zmm1, zmm1:["
Aborted
```

**Comment by practicalswift** [comment]
Test case in #183.

**Comment by practicalswift** [comment]
These seem to be the same issue:

```
$ kstool x64 "vaddpd zmm0{k1},zmm0,mm0:0"
Aborted
$ kstool x64 "vminps zmm0{k1},zmm0,mm0:0"
Aborted
$ kstool x64 "vpsllq zmm0{k1},zmm0,mm0:0"
Aborted
```

**Comment by practicalswift** [comment]
Issue seems to be `Unknown segment register`:

```
$ gdb kstool
Reading symbols from kstool...done.
(gdb) set args x64 'vaddpd zmm1, zmm1, zmm1:['
(gdb) run
Starting program: /usr/local/bin/kstool x64 'vaddpd zmm1, zmm1, zmm1:['

Program received signal SIGABRT, Aborted.
0x00007ffff6eddc37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff6eddc37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff6ee1028 in __GI_abort () at abort.c:89
#2  0x00007ffff74dff60 in llvm::llvm_unreachable_internal (msg=0x7ffff7965220 "Unknown segment register!",
    file=0x7ffff7964c00 "/path/to/keystone/llvm/lib/Target/X86/MCTargetDesc/X86MCCodeEmitter.cpp", line=1154)
    at /path/to/keystone/llvm/lib/Support/ErrorHandling.cpp:71
```

**Comment by aquynh** [comment]
all these issues should be fixed now.

**Comment by practicalswift** [comment]
Confirmed! Thanks! :-)
