### ISSUE TITLE
MIPS branching address

### ISSUE THREAD

**Issue by brendabrandy** [keystone-engine/keystone#237]
I am currently trying to assemble the following MIPS instructions:
```
move $zero, $ra
bal 0x40029c
```
and the starting address is 0x400290. I was wondering whether branches in keystone accept relative or absolute address, and whether it accepts the relative address as words if it accepts relative address. The above assembly code gives me a keystone error. Thanks!

**Comment by aquynh** [comment]
please provide more information: what is the error, and what is your expected encoding at the output?

i believe that the absolute address is expected here.

**Comment by brendabrandy** [comment]
When I try: 
```
move $zero, $ra
bal 0x40029c
```
I got:
```
Traceback (most recent call last):
  File "keystone_single_test.py", line 9, in <module>
    encoding, count = ks.asm(CODE, 0x400290)
  File "/usr/local/lib/python3.5/dist-packages/keystone/keystone.py", line 195, in asm
    raise KsError(errno)
keystone.keystone.KsError: <exception str() failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "keystone_single_test.py", line 12, in <module>
    print("ERROR: %s" %e)
TypeError: __str__ returned non-string (type bytes)

```
However, when I try:
```
move $zero, $ra
bal 0xc
```
I was given:
```
b'move $zero, $ra; bal 0xc' = [37, 0, 224, 3, 94, 255, 17, 4, 0, 0, 0, 0] (number of statements: 2)
```
What does the trailing zeros indicate? Thanks lot for the help!

**Comment by david942j** [comment]
@brendabrandy the trailing zeros is an NOP instruction inserted after branch instructions, see #405
