### ISSUE TITLE
pip doesn't work anymore

### ISSUE THREAD

**Issue by Daniele-B** [keystone-engine/keystone#383]
When i try to install keystone python bindings i goy this.
```
Collecting keystone
  Using cached https://files.pythonhosted.org/packages/f3/a1/32c35b0a81e3f1f78d7db74d5a18cbf3af95bba897f76c3cd18b9da33a26/Keystone-0.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.15.tar.gz
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-CV5Qoc/keystone/setup.py", line 2, in <module>
        use_setuptools('0.6.15')
      File "distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "distribute_setup.py", line 124, in _do_download
        to_dir, download_delay)
      File "distribute_setup.py", line 193, in download_setuptools
        src = urlopen(url)
      File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
        return opener.open(url, data, timeout)
      File "/usr/lib64/python2.7/urllib2.py", line 435, in open
        response = meth(req, response)
      File "/usr/lib64/python2.7/urllib2.py", line 548, in http_response
        'http', request, response, code, msg, hdrs)
      File "/usr/lib64/python2.7/urllib2.py", line 473, in error
        return self._call_chain(*args)
      File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
        result = func(*args)
      File "/usr/lib64/python2.7/urllib2.py", line 556, in http_error_default
        raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
    urllib2.HTTPError: HTTP Error 403: SSL is required
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-CV5Qoc/keystone/
```
How can i solve it?

**Comment by E3V3A** [comment]
They definitely need to re-package this into a new pip release...
