### ISSUE TITLE
Failed to install with pip3 on Ubuntu 16.04 

### ISSUE THREAD

**Issue by hebtuerror404** [keystone-engine/keystone#384]
I'm trying to install keystone-engine with pip3: pip3 install keystone-engine

When it tries to build I get an error:

`Collecting keystone-engine

  Downloading https://files.pythonhosted.org/packages/9a/fc/ed0d3f46921bfaa612d9e8ce8313f99f4149ecf6635659510220c994cb72/keystone-engine-0.9.1-3.tar.gz (2.8MB)
    100% |████████████████████████████████| 2.8MB 83kB/s 
Installing collected packages: keystone-engine
  Running setup.py install for keystone-engine ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-6SJFCV/keystone-engine/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ePkw02/install-record.txt --single-version-externally-managed --compile:
    /usr/local/lib/python2.7/dist-packages/setuptools/dist.py:398: UserWarning: Normalizing '0.9.1-3' to '0.9.1.post3'
      normalized_version,
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/keystone
    copying keystone/__init__.py -> build/lib.linux-x86_64-2.7/keystone
    copying keystone/arm_const.py -> build/lib.linux-x86_64-2.7/keystone
    copying keystone/systemz_const.py -> build/lib.linux-x86_64-2.7/keystone
    copying keystone/hexagon_const.py -> build/lib.linux-x86_64-2.7/keystone
    copying keystone/ppc_const.py -> build/lib.linux-x86_64-2.7/keystone
    copying keystone/arm64_const.py -> build/lib.linux-x86_64-2.7/keystone
    copying keystone/x86_const.py -> build/lib.linux-x86_64-2.7/keystone
    copying keystone/keystone.py -> build/lib.linux-x86_64-2.7/keystone
    copying keystone/sparc_const.py -> build/lib.linux-x86_64-2.7/keystone
    copying keystone/mips_const.py -> build/lib.linux-x86_64-2.7/keystone
    copying keystone/keystone_const.py -> build/lib.linux-x86_64-2.7/keystone
    running build_clib
    running custom_build_clib
    building 'keystone' library
    -- The C compiler identification is GNU 5.4.0
    -- The CXX compiler identification is GNU 5.4.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- The ASM compiler identification is GNU
    -- Found assembler: /usr/bin/cc
    -- Looking for dirent.h
    -- Looking for dirent.h - found
    -- Looking for dlfcn.h
    -- Looking for dlfcn.h - found
    -- Looking for errno.h
    -- Looking for errno.h - found
    -- Looking for execinfo.h
    -- Looking for execinfo.h - found
    -- Looking for fcntl.h
    -- Looking for fcntl.h - found
    -- Looking for inttypes.h
    -- Looking for inttypes.h - found
    -- Looking for limits.h
    -- Looking for limits.h - found
    -- Looking for link.h
    -- Looking for link.h - found
    -- Looking for malloc.h
    -- Looking for malloc.h - found
    -- Looking for malloc/malloc.h
    -- Looking for malloc/malloc.h - not found
    -- Looking for ndir.h
    -- Looking for ndir.h - not found
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Looking for signal.h
    -- Looking for signal.h - found
    -- Looking for stdint.h
    -- Looking for stdint.h - found
    -- Looking for sys/dir.h
    -- Looking for sys/dir.h - found
    -- Looking for sys/ioctl.h
    -- Looking for sys/ioctl.h - found
    -- Looking for sys/mman.h
    -- Looking for sys/mman.h - found
    -- Looking for sys/ndir.h
    -- Looking for sys/ndir.h - not found
    -- Looking for sys/param.h
    -- Looking for sys/param.h - found
    -- Looking for sys/resource.h
    -- Looking for sys/resource.h - found
    -- Looking for sys/stat.h
    -- Looking for sys/stat.h - found
    -- Looking for sys/time.h
    -- Looking for sys/time.h - found
    -- Looking for sys/uio.h
    -- Looking for sys/uio.h - found
    -- Looking for termios.h
    -- Looking for termios.h - found
    -- Looking for unistd.h
    -- Looking for unistd.h - found
    -- Looking for utime.h
    -- Looking for utime.h - found
    -- Looking for zlib.h
    -- Looking for zlib.h - found
    -- Looking for fenv.h
    -- Looking for fenv.h - found
    -- Looking for FE_ALL_EXCEPT
    -- Looking for FE_ALL_EXCEPT - found
    -- Looking for FE_INEXACT
    -- Looking for FE_INEXACT - found
    -- Looking for mach/mach.h
    -- Looking for mach/mach.h - not found
    -- Looking for mach-o/dyld.h
    -- Looking for mach-o/dyld.h - not found
    -- Looking for histedit.h
    -- Looking for histedit.h - not found
    -- Performing Test HAVE_CXXABI_H
    -- Performing Test HAVE_CXXABI_H - Success
    -- Looking for pthread_create in pthread
    -- Looking for pthread_create in pthread - found
    -- Looking for pthread_getspecific in pthread
    -- Looking for pthread_getspecific in pthread - found
    -- Looking for pthread_rwlock_init in pthread
    -- Looking for pthread_rwlock_init in pthread - found
    -- Looking for pthread_mutex_lock in pthread
    -- Looking for pthread_mutex_lock in pthread - found
    -- Looking for dlopen in dl
    -- Looking for dlopen in dl - found
    -- Looking for clock_gettime in rt
    -- Looking for clock_gettime in rt - found
    -- Looking for compress2 in z
    -- Looking for compress2 in z - found
    -- Looking for setupterm in tinfo
    -- Looking for setupterm in tinfo - found
    -- Looking for arc4random
    -- Looking for arc4random - not found
    -- Looking for backtrace
    -- Looking for backtrace - found
    -- Looking for getpagesize
    -- Looking for getpagesize - found
    -- Looking for getrusage
    -- Looking for getrusage - found
    -- Looking for setrlimit
    -- Looking for setrlimit - found
    -- Looking for isatty
    -- Looking for isatty - found
    -- Looking for futimens
    -- Looking for futimens - found
    -- Looking for futimes
    -- Looking for futimes - found
    -- Looking for writev
    -- Looking for writev - found
    -- Looking for mallctl
    -- Looking for mallctl - not found
    -- Looking for mallinfo
    -- Looking for mallinfo - found
    -- Looking for malloc_zone_statistics
    -- Looking for malloc_zone_statistics - not found
    -- Looking for mkdtemp
    -- Looking for mkdtemp - found
    -- Looking for mkstemp
    -- Looking for mkstemp - found
    -- Looking for mktemp
    -- Looking for mktemp - found
    -- Looking for closedir
    -- Looking for closedir - found
    -- Looking for opendir
    -- Looking for opendir - found
    -- Looking for readdir
    -- Looking for readdir - found
    -- Looking for getcwd
    -- Looking for getcwd - found
    -- Looking for gettimeofday
    -- Looking for gettimeofday - found
    -- Looking for getrlimit
    -- Looking for getrlimit - found
    -- Looking for posix_spawn
    -- Looking for posix_spawn - found
    -- Looking for pread
    -- Looking for pread - found
    -- Looking for realpath
    -- Looking for realpath - found
    -- Looking for sbrk
    -- Looking for sbrk - found
    -- Looking for srand48
    -- Looking for srand48 - found
    -- Looking for lrand48
    -- Looking for lrand48 - found
    -- Looking for drand48
    -- Looking for drand48 - found
    -- Looking for strtoll
    -- Looking for strtoll - found
    -- Looking for strtoq
    -- Looking for strtoq - found
    -- Looking for strerror
    -- Looking for strerror - found
    -- Looking for strerror_r
    -- Looking for strerror_r - found
    -- Looking for strerror_s
    -- Looking for strerror_s - not found
    -- Looking for setenv
    -- Looking for setenv - found
    -- Looking for dlerror
    -- Looking for dlerror - found
    -- Looking for dlopen
    -- Looking for dlopen - found
    -- Looking for __GLIBC__
    -- Looking for __GLIBC__ - found
    -- Performing Test HAVE_INT64_T
    -- Performing Test HAVE_INT64_T - Success
    -- Performing Test HAVE_UINT64_T
    -- Performing Test HAVE_UINT64_T - Success
    -- Performing Test HAVE_U_INT64_T
    -- Performing Test HAVE_U_INT64_T - Success
    -- Performing Test HAVE_CXX_ATOMICS_WITHOUT_LIB
    -- Performing Test HAVE_CXX_ATOMICS_WITHOUT_LIB - Success
    -- Performing Test LLVM_HAS_ATOMICS
    -- Performing Test LLVM_HAS_ATOMICS - Success
    -- Performing Test SUPPORTS_NO_VARIADIC_MACROS_FLAG
    -- Performing Test SUPPORTS_NO_VARIADIC_MACROS_FLAG - Success
    -- Performing Test HAS_MAYBE_UNINITIALIZED
    -- Performing Test HAS_MAYBE_UNINITIALIZED - Success
    -- Target triple: x86_64-unknown-linux-gnu
    -- Native target architecture is X86
    -- Threads enabled.
    -- Performing Test C_SUPPORTS_FPIC
    -- Performing Test C_SUPPORTS_FPIC - Success
    -- Performing Test CXX_SUPPORTS_FPIC
    -- Performing Test CXX_SUPPORTS_FPIC - Success
    -- Building with -fPIC
    -- Performing Test SUPPORTS_FVISIBILITY_INLINES_HIDDEN_FLAG
    -- Performing Test SUPPORTS_FVISIBILITY_INLINES_HIDDEN_FLAG - Success
    -- Performing Test CXX_SUPPORTS_MISSING_FIELD_INITIALIZERS_FLAG
    -- Performing Test CXX_SUPPORTS_MISSING_FIELD_INITIALIZERS_FLAG - Success
    -- Performing Test C_SUPPORTS_COVERED_SWITCH_DEFAULT_FLAG
    -- Performing Test C_SUPPORTS_COVERED_SWITCH_DEFAULT_FLAG - Failed
    -- Performing Test CXX_SUPPORTS_COVERED_SWITCH_DEFAULT_FLAG
    -- Performing Test CXX_SUPPORTS_COVERED_SWITCH_DEFAULT_FLAG - Failed
    -- Performing Test C_SUPPORTS_DELETE_NON_VIRTUAL_DTOR_FLAG
    -- Performing Test C_SUPPORTS_DELETE_NON_VIRTUAL_DTOR_FLAG - Failed
    -- Performing Test CXX_SUPPORTS_DELETE_NON_VIRTUAL_DTOR_FLAG
    -- Performing Test CXX_SUPPORTS_DELETE_NON_VIRTUAL_DTOR_FLAG - Success
    -- Performing Test C_WCOMMENT_ALLOWS_LINE_WRAP
    -- Performing Test C_WCOMMENT_ALLOWS_LINE_WRAP - Failed
    -- Performing Test CXX_SUPPORTS_CXX11
    -- Performing Test CXX_SUPPORTS_CXX11 - Success
    -- Performing Test C_SUPPORTS_FNO_FUNCTION_SECTIONS
    -- Performing Test C_SUPPORTS_FNO_FUNCTION_SECTIONS - Success
    -- Performing Test C_SUPPORTS_FFUNCTION_SECTIONS
    -- Performing Test C_SUPPORTS_FFUNCTION_SECTIONS - Success
    -- Performing Test CXX_SUPPORTS_FFUNCTION_SECTIONS
    -- Performing Test CXX_SUPPORTS_FFUNCTION_SECTIONS - Success
    -- Performing Test C_SUPPORTS_FDATA_SECTIONS
    -- Performing Test C_SUPPORTS_FDATA_SECTIONS - Success
    -- Performing Test CXX_SUPPORTS_FDATA_SECTIONS
    -- Performing Test CXX_SUPPORTS_FDATA_SECTIONS - Success
    -- Found PythonInterp: /usr/local/bin/python2.7 (found version "2.7.13")
    -- Constructing LLVMBuild project information
    CMake Error at llvm/CMakeLists.txt:394 (message):
      Unexpected failure executing llvm-build: Traceback (most recent call last):
    
        File "/tmp/pip-install-6SJFCV/keystone-engine/src/llvm/utils/llvm-build/llvm-build", line 3, in <module>
          import llvmbuild
        File "/tmp/pip-install-6SJFCV/keystone-engine/src/llvm/utils/llvm-build/llvmbuild/__init__.py", line 1, in <module>
          from llvmbuild.main import main
        File "/tmp/pip-install-6SJFCV/keystone-engine/src/llvm/utils/llvm-build/llvmbuild/main.py", line 2, in <module>
          import filecmp
        File "/usr/local/lib/python2.7/filecmp.py", line 14, in <module>
          from itertools import ifilter, ifilterfalse, imap, izip
    
      ImportError: No module named itertools
    
    
    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-install-6SJFCV/keystone-engine/src/build/CMakeFiles/CMakeOutput.log".
    See also "/tmp/pip-install-6SJFCV/keystone-engine/src/build/CMakeFiles/CMakeError.log".
    running install_lib
    running install_data
    error: can't copy 'src/build/llvm/lib/libkeystone.so': doesn't exist or not a regular file
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-6SJFCV/keystone-engine/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ePkw02/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-6SJFCV/keystone-engine/
`

**Comment by amlamarra** [comment]
Same here. I'm unable to install it.

```
Collecting keystone-engine
  Downloading https://files.pythonhosted.org/packages/9a/fc/ed0d3f46921bfaa612d9e8ce8313f99f4149ecf6635659510220c994cb72/keystone-engine-0.9.1-3.tar.gz (2.8MB)
    100% |████████████████████████████████| 2.8MB 16.6MB/s
Installing collected packages: keystone-engine
  Running setup.py install for keystone-engine ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-1o_50m3z/keystone-engine/setup.py';f=getattr(tok
enize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-xv5uj1af/in
stall-record.txt --single-version-externally-managed --compile:
    /usr/lib/python3/dist-packages/setuptools/dist.py:285: UserWarning: Normalizing '0.9.1-3' to '0.9.1.post3'
      normalized_version,
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/keystone
    copying keystone/__init__.py -> build/lib/keystone
    copying keystone/arm64_const.py -> build/lib/keystone
    copying keystone/arm_const.py -> build/lib/keystone
    copying keystone/hexagon_const.py -> build/lib/keystone
    copying keystone/keystone.py -> build/lib/keystone
    copying keystone/keystone_const.py -> build/lib/keystone
    copying keystone/mips_const.py -> build/lib/keystone
    copying keystone/ppc_const.py -> build/lib/keystone
    copying keystone/sparc_const.py -> build/lib/keystone
    copying keystone/systemz_const.py -> build/lib/keystone
    copying keystone/x86_const.py -> build/lib/keystone
    running build_clib
    running custom_build_clib
    building 'keystone' library
    ../make-share.sh: 21: ../make-share.sh: cmake: not found
    running install_lib
    running install_data
    error: can't copy 'src/build/llvm/lib/libkeystone.so': doesn't exist or not a regular file

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-1o_50m3z/keystone-engine/setup.py';f=getattr(tokenize, 'open', open)(__f
ile__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-xv5uj1af/install-record.txt --singl
e-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-1o_50m3z/keystone-engine/
```

**Comment by amlamarra** [comment]
I think my problem with this was not having cmake installed.
