### ISSUE TITLE
Fail to load dynamic library

### ISSUE THREAD

**Issue by bannsec** [keystone-engine/keystone#386]
I think this issue was fixed in #301 but the version in pypi was pushed way back in Aug 2016...

```
ImportError: ERROR: fail to load the dynamic library.
```

This is after installing via pip install keystone-engine into a python virtualenv.

**Comment by bannsec** [comment]
Also just found a fun install bug in the current pypi release. However the library is being packaged is _very_ wrong:

```
/home/angr/.virtualenvs/patchkit/lib/python2.7/site-packages/home/angr/.virtualenvs/patchkit/lib/python2.7/site-packages/keystone/libkeystone.so
```

That's not a typo. It recreated the entire path as a sub-path.

**Comment by Slurpgeit** [comment]
Oh wow, +1 for this. You just solved my month old problem.

**Comment by bannsec** [comment]
From what I can tell, this issue might actually be fixed. However, nobody has bothered to push an update to pypi since July 2016. Building from source appears to install the .so file correctly.

Anyone wanna actually push an update plz? Should we expect that the python library is not going to be maintained?

**Comment by Inndy** [comment]
@aquynh Please push a new version to pypi

**Comment by aquynh** [comment]
looking for somebody who can help to review pull reqs, as well as improving
the Python package (pypi).
this is what i want to do, before the new release.

**Comment by caizixian** [comment]
FWIW, when I installed `keystone-engine` with `pip install --user` (Python 3.7), the installation works fine. But when I used Python 3.6, it failed.

**Comment by caizixian** [comment]
OK. I narrow the problem down to whether wheel is built during the installation.
Try `pip3 install --user -U --no-cache-dir --force-reinstall --no-binary keystone-engine keystone-engine` as a workaround.

**Comment by wtdcode** [comment]
> OK. I narrow the problem down to whether wheel is built during the installation.
> Try `pip3 install --user -U --no-cache-dir --force-reinstall --no-binary keystone-engine keystone-engine` as a workaround.
> YMMV.

Great! Works for me.

**Comment by gmagno** [comment]
Hey, I'm also having problems with keystone python bindings installation.
`pip install keystone-engine` apparently works fine, with no errors. But when I try to import keystone, it fails with:
```
(.venv)  .venv/opt/gdb $ python
Python 3.7.5 (default, Nov  7 2019, 10:50:52)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import keystone
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/gdb/.venv/lib/python3.7/site-packages/keystone/__init__.py", line 4, in <module>
    from .keystone import Ks, ks_version, ks_arch_supported, version_bind, debug, KsError, __version__
  File "/opt/gdb/.venv/lib/python3.7/site-packages/keystone/keystone.py", line 75, in <module>
    raise ImportError("ERROR: fail to load the dynamic library.")
ImportError: ERROR: fail to load the dynamic library.
```

![image](https://user-images.githubusercontent.com/46817915/82173196-c2e2f880-98a2-11ea-9c56-e1d4709961b9.png)

**Comment by bannsec** [comment]
Yep. Still waiting for keystone to push a new release.

**Comment by 0xjacklove** [comment]
because the file /usr/local/lib/libkeystone.dylib is missing.
The following commands solved my problem.
brew install cmake
git clone https://github.com/keystone-engine/keystone.git
cd keystone
mkdir build
cd build
../make-share.sh
sudo make install

**Comment by kotori2** [comment]
I ran into this issue with recent CMake versions and it turns out that the cmake errors were completely ignored: 
```
CMake Error at CMakeLists.txt:4 (cmake_minimum_required):
    Compatibility with CMake < 3.5 has been removed from CMake.

    Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
    to tell CMake that the project requires at least <min> but has been updated
    to work with policies introduced by <max> or earlier.

    Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.

```

The solution is straightforward: 
1. Change `cmake_minimum_required` to 3.5 or higher
2. Remove the block that uses old behavior of `POLICY CMP0051`
