### ISSUE TITLE
NameError: name 'Ks' is not defined (Kali Linux)

### ISSUE THREAD

**Issue by tvvoorst** [keystone-engine/keystone#498]
Hi I am getting an error after installing keystone-engine using both pip and pip3. I know there are people with similar issues on Kali specifically.

Keystone-engine is installed:
```
pip3 install keystone-engine
Requirement already satisfied: keystone-engine in /usr/local/lib/python3.9/dist-packages (0.9.2)
pip install keystone-engine
Requirement already satisfied: keystone-engine in /usr/local/lib/python3.9/dist-packages (0.9.2)
```

The error I am getting:
```
Traceback (most recent call last):
  File "/pathtofile/keystone.py", line 2, in <module>
    from keystone import *
  File "/pathtofile/keystone.py", line 14, in <module>
    ks = Ks(KS_ARCH_X86, KS_MODE_32)
NameError: name 'Ks' is not defined
```

The script I try to run:
```
#!/usr/bin/python
from keystone import *

CODE = (
"                      "
" start:               "
"     xor eax, eax    ;"
"     add eax, ecx    ;"
"     push eax        ;"
"     pop esi         ;"
)

# Initialize engine in 32bit mode
ks = Ks(KS_ARCH_X86, KS_MODE_32)
encoding, count = ks.asm(CODE)
instructions = ""
for dec in encoding:
    instructions += "\\x{0:02x}".format(int(dec)).rstrip("\n")

print("Opcodes = (\"" + instructions + "\")")

```

If I neeed to provide any additional information please let me know

**Comment by tvvoorst** [comment]
should not have named the file keystone.py....... layer 8 error
